# Generated by Django 5.1.4 on 2025-01-12 04:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0015_review_meta'),
        ('player', '0048_alter_appeal_status'),
        ('venue', '0018_alter_venue_tz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date', models.DateField()),
                ('hours', models.BinaryField(default=b'\x00\x00\x00')),
                ('log', models.JSONField(default=list)),
                ('meta', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('A', 'active'), ('C', 'cancelled'), ('D', 'dormant'), ('X', 'expired')], default='A', max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('invitees', models.ManyToManyField(related_name='invitees', to='player.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.BinaryField(default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', null=True)),
                ('strength', models.CharField(choices=[('W', 'much-weaker'), ('w', 'weaker'), ('m', 'matched'), ('s', 'stronger'), ('S', 'much-stonger'), ('z', 'unknown')], default='m', max_length=1)),
                ('str_conf', models.CharField(choices=[('a', ''), ('b', 'probably'), ('c', 'maybe'), ('z', 'unknown')], default='z', max_length=1)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeal.appeal')),
                ('rival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
        ),
        migrations.AddField(
            model_name='appeal',
            name='rivals',
            field=models.ManyToManyField(related_name='rivals', through='appeal.Bid', to='player.player'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.UniqueConstraint(fields=('date', 'game', 'player', 'venue'), name='unique_appeal'),
        ),
    ]
