# Generated by Django 5.1.4 on 2025-01-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
        ('player', '0050_remove_bid_appeal_remove_bid_rival_delete_appeal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='invitees',
            field=models.ManyToManyField(related_name='invitees', to='player.friend'),
        ),
    ]
