# Generated by Django 5.2.9 on 2026-01-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0002_alter_appeal_invitees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='hours',
            field=models.BinaryField(default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'),
        ),
    ]
