# Generated by Django 5.0.2 on 2024-09-17 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('game', '0008_rename_rivals_match_competitors'),
        ('venue', '0009_venue_address_venue_admin1_venue_country_venue_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin1', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(max_length=2)),
                ('east', models.DecimalField(decimal_places=6, default=180, max_digits=9)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('north', models.DecimalField(decimal_places=6, default=90, max_digits=9)),
                ('south', models.DecimalField(decimal_places=6, default=-90, max_digits=9)),
                ('west', models.DecimalField(decimal_places=6, default=-180, max_digits=9)),
                ('locality', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venue.venue')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
    ]
