# Generated by Django 5.0.2 on 2024-09-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_region_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
