# Generated by Django 5.0.2 on 2024-10-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_region_lat_region_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='placeid',
            field=models.TextField(default='invalid'),
            preserve_default=False,
        ),
    ]
