# Generated by Django 5.0.2 on 2024-10-08 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_region_placeid'),
        ('venue', '0012_place_admin1_place_country_place_locality_place_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='region',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='venue',
        ),
        migrations.AddField(
            model_name='mark',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='venue.place'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
