# Generated by Django 5.0.2 on 2024-10-06 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_region_placeid'),
        ('venue', '0010_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venue.region'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
