# Generated by Django 5.0.2 on 2024-12-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_mark_region_remove_mark_venue_mark_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='content',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
