# Generated by Django 5.1.4 on 2025-02-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='version',
            field=models.CharField(default='', editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
