# Generated by Django 5.1.4 on 2025-02-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('_', ''), ('B', 'Bug'), ('U', 'Something is not clear'), ('D', 'Something is too dfficult'), ('G', 'Something is really good'), ('I', 'Suggestion for improvement'), ('O', 'Other')], default='_', max_length=1),
        ),
    ]
