# Generated by Django 5.1.4 on 2025-02-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedback_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='commit',
            field=models.CharField(default='', editable=False, max_length=40),
            preserve_default=False,
        ),
    ]
