# Generated by Django 5.1.4 on 2025-02-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_feedback_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='issue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
