# Generated by Django 5.2.9 on 2026-03-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_feedback_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('_', ''), ('B', 'Bug'), ('U', 'Something is not clear'), ('D', 'Something is too dfficult'), ('G', 'Something is really good'), ('I', 'Suggestion for improvement'), ('T', 'Translation issue'), ('O', 'Other')], default='_', max_length=1),
        ),
    ]
