# Generated by Django 5.2.9 on 2026-06-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_alter_feedback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('B', 'Bug'), ('U', 'Something is not clear'), ('D', 'Something is too difficult'), ('G', 'Something is really good'), ('I', 'Suggestion for improvement'), ('T', 'Translation issue'), ('V', 'Venue issue'), ('O', 'Other')], max_length=1),
        ),
    ]
