# Generated by Django 5.0.2 on 2024-03-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(to='game.game'),
        ),
    ]
