# Generated by Django 5.0.2 on 2024-03-12 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('player', '0006_precis'),
        ('venue', '0002_venue_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('hours', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.SmallIntegerField(blank=True)),
                ('strength', models.CharField(choices=[('W', 'much-weaker'), ('w', 'weaker'), ('M', 'matched'), ('s', 'stronger'), ('S', 'much-stonger')], max_length=1)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.appeal')),
                ('rival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
        ),
        migrations.AddField(
            model_name='appeal',
            name='rivals',
            field=models.ManyToManyField(through='player.Invite', to='player.appeal'),
        ),
    ]
