# Generated by Django 5.0.2 on 2024-03-12 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_appeal_invite_appeal_rivals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
                ('rival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.opinion')),
            ],
        ),
    ]
