# Generated by Django 5.0.2 on 2024-03-12 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_opinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.BooleanField()),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.opinion')),
            ],
        ),
    ]
