# Generated by Django 5.0.2 on 2024-03-12 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_conduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative', models.CharField(choices=[('W', 'much-weaker'), ('w', 'weaker'), ('M', 'matched'), ('s', 'stronger'), ('S', 'much-stonger')], max_length=1)),
                ('weight', models.PositiveSmallIntegerField()),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.opinion')),
            ],
        ),
    ]
