# Generated by Django 5.0.2 on 2024-03-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='icon',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
