# Generated by Django 5.0.2 on 2024-03-13 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_remove_player_icon_delete_social'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='location_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='notify_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
