# Generated by Django 5.0.2 on 2024-03-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_alter_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='location_auto',
        ),
        migrations.RemoveField(
            model_name='player',
            name='notify_email',
        ),
        migrations.RemoveField(
            model_name='player',
            name='notify_web',
        ),
    ]
