# Generated by Django 5.0.2 on 2024-03-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_remove_player_location_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precis',
            name='text',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
