# Generated by Django 5.0.2 on 2024-04-13 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0017_alter_invite_strength_alter_strength_relative_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='available',
            old_name='week',
            new_name='hours',
        ),
    ]
