# Generated by Django 5.0.2 on 2024-04-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_icon'),
        ('player', '0018_rename_week_available_hours'),
        ('venue', '0007_alter_venue_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='available',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='available',
            constraint=models.UniqueConstraint(fields=('game', 'player', 'venue'), name='unique_availability'),
        ),
    ]
