# Generated by Django 5.0.2 on 2024-05-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0023_alter_invite_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='log',
            field=models.JSONField(default=[]),
        ),
    ]
