# Generated by Django 5.0.2 on 2024-05-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0024_appeal_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='log',
            field=models.JSONField(default=list),
        ),
    ]
