# Generated by Django 5.0.2 on 2024-09-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0027_filter_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Available',
        ),
    ]
