# Generated by Django 5.0.2 on 2024-09-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0028_delete_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='hours',
            field=models.BinaryField(default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='hours',
            field=models.BinaryField(default=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', null=True),
        ),
    ]
