# Generated by Django 5.0.2 on 2024-09-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0029_alter_filter_hours_alter_invite_hours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invite',
            new_name='Bid',
        ),
    ]
