# Generated by Django 5.0.2 on 2024-10-07 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_rename_rivals_match_competitors'),
        ('player', '0030_rename_invite_bid'),
        ('venue', '0012_place_admin1_place_country_place_locality_place_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='filter',
            name='unique_filter',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='venue',
        ),
        migrations.AddField(
            model_name='filter',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venue.place'),
        ),
        migrations.AddConstraint(
            model_name='filter',
            constraint=models.UniqueConstraint(fields=('game', 'place', 'player'), name='unique_filter'),
        ),
    ]
