# Generated by Django 5.0.2 on 2024-10-08 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0032_alter_appeal_venue'),
        ('venue', '0016_venue_games_venue_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venue'),
        ),
    ]
