# Generated by Django 5.0.2 on 2024-10-29 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0033_alter_appeal_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='player.player'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='rival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to='player.player'),
        ),
    ]
