# Generated by Django 5.0.2 on 2024-10-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0034_alter_opinion_player_alter_opinion_rival'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='conduct',
            field=models.BinaryField(default=b'\x00\x00\x00'),
        ),
        migrations.DeleteModel(
            name='Conduct',
        ),
    ]
