# Generated by Django 5.0.2 on 2024-11-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0036_remove_strength_opinion_strength_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='strengths',
            field=models.ManyToManyField(to='player.strength'),
        ),
    ]
