# Generated by Django 5.0.2 on 2024-11-02 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_match_complete'),
        ('player', '0037_friend_strengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='strength',
            name='game',
            field=models.ForeignKey(default='squ', on_delete=django.db.models.deletion.CASCADE, to='game.game'),
            preserve_default=False,
        ),
    ]
