# Generated by Django 5.0.2 on 2024-11-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0038_strength_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
