# Generated by Django 5.0.2 on 2024-11-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_match_meta'),
        ('player', '0039_appeal_meta'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='strength',
            constraint=models.UniqueConstraint(fields=('game', 'player', 'rival'), name='unique_relative'),
        ),
    ]
