# Generated by Django 5.0.2 on 2024-12-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0041_bid_str_conf_alter_bid_strength_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='str_conf',
            field=models.CharField(choices=[('a', ''), ('b', 'probably'), ('c', 'maybe'), ('z', 'unknown')], default='z', max_length=1),
        ),
        migrations.AlterField(
            model_name='strength',
            name='relative',
            field=models.CharField(choices=[('W', 'much-weaker'), ('w', 'weaker'), ('m', 'matched'), ('s', 'stronger'), ('S', 'much-stonger')], max_length=1),
        ),
    ]
