# Generated by Django 5.0.2 on 2024-12-03 01:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0042_alter_bid_str_conf_alter_strength_relative'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
