# Generated by Django 5.0.2 on 2024-12-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0043_appeal_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('email', 'player'), name='unique_friend'),
        ),
    ]
