# Generated by Django 5.0.2 on 2024-12-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0044_alter_friend_email_friend_unique_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('A', 'active'), ('D', 'dormant'), ('X', 'cancelled')], default='A', max_length=1),
        ),
    ]
