# Generated by Django 5.0.2 on 2024-12-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0045_appeal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='rivals',
            field=models.ManyToManyField(related_name='rivals', through='player.Bid', to='player.player'),
        ),
    ]
