# Generated by Django 5.0.2 on 2024-12-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0046_alter_appeal_rivals'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='invitees',
            field=models.ManyToManyField(related_name='invitees', to='player.player'),
        ),
    ]
