# Generated by Django 5.1.4 on 2025-01-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0047_appeal_invitees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('A', 'active'), ('C', 'cancelled'), ('D', 'dormant'), ('X', 'expired')], default='A', max_length=1),
        ),
    ]
