# Generated by Django 5.1.4 on 2025-01-12 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_review_meta'),
        ('player', '0048_alter_appeal_status'),
        ('venue', '0018_alter_venue_tz'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appeal',
            name='unique_appeal',
        ),
        migrations.AlterField(
            model_name='appeal',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.game'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='invitees',
            field=models.ManyToManyField(related_name='invitees_migration', to='player.player'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.player'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='rivals',
            field=models.ManyToManyField(related_name='rivals_migration', through='player.Bid', to='player.player'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='venue.venue'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='rival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='player.player'),
        ),
    ]
