# Generated by Django 5.1.4 on 2025-01-12 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0049_remove_appeal_unique_appeal_alter_appeal_game_and_more'),
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='appeal',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='rival',
        ),
        migrations.DeleteModel(
            name='Appeal',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
