# Generated by Django 5.1.4 on 2025-01-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0050_remove_bid_appeal_remove_bid_rival_delete_appeal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='blocked',
        ),
    ]
