# Generated by Django 5.1.4 on 2025-01-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0051_remove_player_blocked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Precis',
        ),
    ]
