# Generated by Django 5.2.9 on 2026-01-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0052_delete_precis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='hours',
            field=models.BinaryField(default=b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'),
        ),
    ]
