# Generated by Django 5.2.9 on 2026-02-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0053_alter_filter_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='email_hash',
            new_name='hash',
        ),
    ]
