# Generated by Django 5.0.2 on 2024-03-12 23:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Persona',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='profile',
            new_name='persona',
        ),
    ]
