# Generated by Django 5.0.2 on 2024-03-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='location_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='notify_web',
            field=models.BooleanField(default=False),
        ),
    ]
