# Generated by Django 5.0.2 on 2024-12-16 22:19

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_alter_person_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='alerts',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
