# Generated by Django 5.1.4 on 2025-01-18 00:08

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_alter_person_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockee', to='person.person'),
        ),
        migrations.AddField(
            model_name='block',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker', to='person.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='block',
            field=models.ManyToManyField(blank=True, through='person.Block', to='person.person'),
        ),
    ]
