# Generated by Django 5.1.4 on 2025-02-24 01:07

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_alter_language'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='social',
            constraint=models.UniqueConstraint(fields=('person', 'url'), name='unique_social'),
        ),
    ]
