# Generated by Django 5.1.7 on 2025-04-10 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0016_constrain_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='alerts',
        ),
        migrations.AddField(
            model_name='alert',
            name='person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='repeats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
