# Generated by Django 5.1.7 on 2025-04-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0017_remove_person_alerts_alert_person_alert_repeats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[(32, 'new_bid'), (33, 'cancel_bid'), (34, 'decline_bid'), (48, 'new_match'), (49, 'cancel_match'), (50, 'chat_match')], max_length=1),
        ),
    ]
