# Generated by Django 5.1.7 on 2025-04-10 04:37

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0019_alert_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='context',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
