# Generated by Django 5.1.7 on 2025-04-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0020_alert_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('a', 'new_bid'), ('b', 'cancel_bid'), ('c', 'decline_bid'), ('f', 'new_match'), ('g', 'cancel_match'), ('h', 'chat_match')], max_length=1),
        ),
    ]
