# Generated by Django 5.1.7 on 2025-04-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0023_alter_person_notify_email_alter_person_notify_web'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='notify_web',
            new_name='notify_push',
        ),
        migrations.AlterField(
            model_name='alert',
            name='mode',
            field=models.CharField(choices=[('E', 'Email'), ('P', 'Push')], max_length=1),
        ),
    ]
