# Generated by Django 5.1.7 on 2025-04-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0024_rename_notify_web_person_notify_push_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='text',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='alert',
            name='expires',
            field=models.DateTimeField(),
        ),
    ]
