# Generated by Django 5.2.9 on 2026-01-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0025_rename_text_alert_url_alter_alert_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('a', 'woo_invite'), ('b', 'rival_invite'), ('k', 'new_bid'), ('l', 'cancel_bid'), ('m', 'decline_bid'), ('p', 'new_match'), ('q', 'cancel_match'), ('r', 'chat_match')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='notify_email',
            field=models.CharField(default='kmpq', max_length=64),
        ),
    ]
