# Generated by Django 5.2.9 on 2026-01-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0026_alter_alert_type_alter_person_notify_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='mode',
            field=models.CharField(choices=[('E', 'Email'), ('P', 'Push'), ('U', 'UI')], max_length=1),
        ),
    ]
