# Generated by Django 5.2.9 on 2026-02-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0027_alter_alert_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('a', 'woo_invite'), ('b', 'rival_invite'), ('c', 'filter_invite'), ('k', 'new_bid'), ('l', 'cancel_bid'), ('m', 'decline_bid'), ('p', 'new_match'), ('q', 'cancel_match'), ('r', 'chat_match'), ('s', 'review_match')], max_length=1),
        ),
    ]
