# Generated by Django 5.2.9 on 2026-02-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0028_alter_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='language',
            field=models.CharField(choices=[('bg', 'български'), ('en', 'English'), ('it', 'italiano')], default='en', max_length=2),
        ),
    ]
