# Generated by Django 5.2.9 on 2026-02-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0029_alter_person_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='language',
            field=models.CharField(choices=[('ar', 'اللغة العربية'), ('bg', 'български'), ('en', 'English'), ('it', 'italiano')], default='en', max_length=2),
        ),
    ]
