# Generated by Django 5.2.9 on 2026-03-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0031_alter_person_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='language',
            field=models.CharField(choices=[('ar', 'اللغة العربية'), ('bg', 'български'), ('en', 'English'), ('it', 'italiano'), ('ur', 'اردو'), ('zh', '中文')], default='en', max_length=2),
        ),
    ]
