# Generated by Django 5.2.9 on 2026-03-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0033_alter_person_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='language',
            field=models.CharField(choices=[('ar', 'اللغة العربية'), ('bg', 'български'), ('en', 'English'), ('it', 'italiano'), ('ms', 'Bahasa Melayu'), ('ur', 'اردو'), ('zh', '中文')], default='', max_length=2),
        ),
    ]
