# Generated by Django 5.0.2 on 2024-03-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_manager_venue_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='icon',
        ),
    ]
