# Generated by Django 5.0.2 on 2024-03-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_remove_manager_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='location_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manager',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='notify_web',
            field=models.BooleanField(default=False),
        ),
    ]
