# Generated by Django 5.0.2 on 2024-04-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_alter_manager_location_auto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='location_auto',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='notify_email',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='notify_web',
        ),
    ]
