# Generated by Django 5.0.2 on 2024-10-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0010_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, default=-36.449786, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, default=146.430037, max_digits=9)),
                ('placeid', models.TextField()),
            ],
        ),
    ]
