# Generated by Django 5.0.2 on 2024-10-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0011_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='admin1',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='locality',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
