# Generated by Django 5.0.2 on 2024-10-08 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0012_place_admin1_place_country_place_locality_place_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='admin1',
        ),
        migrations.RemoveField(
            model_name='region',
            name='country',
        ),
        migrations.RemoveField(
            model_name='region',
            name='id',
        ),
        migrations.RemoveField(
            model_name='region',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='region',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='region',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='placeid',
        ),
        migrations.AddField(
            model_name='region',
            name='place_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='venue.place'),
            preserve_default=False,
        ),
    ]
