# Generated by Django 5.0.2 on 2024-10-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_match_venue'),
        ('venue', '0015_remove_venue_admin1_remove_venue_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='games',
            field=models.ManyToManyField(to='game.game'),
        ),
        migrations.AddField(
            model_name='venue',
            name='managers',
            field=models.ManyToManyField(blank=True, to='venue.manager'),
        ),
    ]
