# Generated by Django 5.2.9 on 2026-03-05 04:59

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0018_alter_venue_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='flags',
            field=bitfield.models.BitField((), default=0),
        ),
    ]
