# Generated by Django 5.2.9 on 2026-03-05 05:55

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0019_venue_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='flags',
            field=bitfield.models.BitField('proposed', default=0),
        ),
    ]
