# Generated by Django 5.2.9 on 2026-03-05 06:50

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0020_alter_venue_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='flags',
            field=bitfield.models.BitField(('proposed',), default=0),
        ),
    ]
