# Generated by Django 5.0.2 on 2024-04-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.CharField(default='fa-solid fa-8', max_length=32),
            preserve_default=False,
        ),
    ]
