# Generated by Django 5.0.2 on 2024-04-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.CharField(max_length=48),
        ),
    ]
