# Generated by Django 5.0.2 on 2024-05-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='log',
            field=models.JSONField(default=list),
        ),
    ]
