# Generated by Django 5.0.2 on 2024-05-04 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_match_log'),
        ('player', '0025_alter_appeal_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='appeal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player.appeal'),
        ),
    ]
