# Generated by Django 5.0.2 on 2024-05-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_match_appeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='appeal',
        ),
    ]
