# Generated by Django 5.0.2 on 2024-05-15 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_match_appeal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='rivals',
            new_name='competitors',
        ),
    ]
