# Generated by Django 5.0.2 on 2024-10-08 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_rename_rivals_match_competitors'),
        ('venue', '0013_remove_region_admin1_remove_region_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.place'),
        ),
    ]
