# Generated by Django 5.0.2 on 2024-10-31 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_match_venue'),
        ('player', '0036_remove_strength_opinion_strength_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='player.player')),
                ('rival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to='player.player')),
            ],
        ),
    ]
