# Generated by Django 5.0.2 on 2024-10-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
