# Generated by Django 5.0.2 on 2024-11-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_match_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='complete',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('A', 'active'), ('C', 'complete'), ('X', 'cancelled')], default='A', max_length=1),
        ),
    ]
