# Generated by Django 5.0.2 on 2024-11-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_match_complete_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
