# Generated by Django 5.0.2 on 2024-12-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_match_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
