# Generated by Django 5.2.9 on 2026-01-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_review_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('A', 'active'), ('C', 'complete'), ('D', 'disabled'), ('X', 'cancelled')], default='A', max_length=1),
        ),
    ]
