# Generated by Django 5.2.9 on 2026-02-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name_bg',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='name_en',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
