# Generated by Django 5.2.9 on 2026-02-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_game_name_bg_game_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name_it',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
