# Generated by Django 5.2.9 on 2026-02-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_game_name_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name_ar',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
