# Generated by Django 5.2.9 on 2026-03-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_game_name_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name_ur',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
