# Generated by Django 5.2.9 on 2026-03-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_game_name_ur'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name_zh',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
