# Generated by Django 5.2.9 on 2026-03-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_game_name_zh'),
        ('player', '0054_rename_email_hash_player_hash'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('match', 'player', 'rival'), name='unique_review'),
        ),
    ]
