# Generated by Django 5.2.9 on 2026-03-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_review_unique_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name_ms',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
