# Generated by Django 5.0.2 on 2024-03-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('bg', 'български'), ('en', 'English'), ('es', 'Español'), ('zh', '中文'), ('ru', 'русский'), ('fr', 'Français'), ('hi', 'हिंदी'), ('ar', 'اللغة العربية'), ('jp', '日本語')], default='en', max_length=2),
        ),
    ]
