# Generated by Django 5.0.2 on 2024-03-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
