# Generated by Django 5.0.2 on 2024-03-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
    ]
