# Generated by Django 5.2.9 on 2026-02-06 20:34

import authenticate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_remove_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash',
            field=models.CharField(db_index=True, default=authenticate.models.uuid4_hex, max_length=32, null=True),
        ),
    ]
