# Generated by Django 5.2.9 on 2026-02-06 20:35

from django.db import migrations
from hashlib import md5
from uuid import uuid4


def gen_hash(apps, schema_editor):
    User = apps.get_model("authenticate", "User")
    for row in User.objects.all():
        row.hash = md5(row.email.encode()).hexdigest()
        row.save(update_fields=["hash"])


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_user_hash'),
    ]

    operations = [
        migrations.RunPython(
            gen_hash,
            reverse_code=migrations.RunPython.noop
        ),
    ]
