# Generated by Django 5.2.9 on 2026-02-06 20:35

import authenticate.models
from django.db import migrations, models
from uuid import uuid4


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_user_hash_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hash',
            field=models.CharField(db_index=True, default=authenticate.models.uuid4_hex, max_length=32, unique=True),
        ),
    ]
